services:
  - type: pserv
    name: taskmanager-db
    plan: starter

  - type: web
    name: taskmanager-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile.prod
    plan: starter
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: taskmanager.settings.production
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanager-db
          property: connectionString