services:
  # PostgreSQL Database
  - type: pserv
    name: taskmanager-db
    plan: starter
    databaseName: taskmanager
    user: taskmanager_user

  # Redis Cache
  - type: redis
    name: taskmanager-redis
    plan: starter
    ipAllowList: []

  # Django Backend API
  - type: web
    name: taskmanager-backend
    dockerfilePath: ./backend/Dockerfile.prod
    plan: starter
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /health/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: taskmanager.settings.production
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanager-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: taskmanager-redis
          property: connectionString
      - key: ALLOWED_HOSTS
        value: taskmanager-backend.onrender.com,localhost,127.0.0.1
      - key: CORS_ALLOWED_ORIGINS
        value: https://taskmanager-frontend.onrender.com,http://localhost:3000
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: GUNICORN_WORKERS
        value: "2"
      - key: LOG_LEVEL
        value: "INFO"
    disk:
      name: backend-disk
      mountPath: /app/media
      sizeGB: 1

  # React Frontend
  - type: static
    name: taskmanager-frontend
    buildCommand: cd frontend && chmod +x build.sh && ./build.sh
    staticPublishPath: ./frontend/build
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: REACT_APP_API_URL
        value: https://taskmanager-backend.onrender.com
      - key: REACT_APP_WS_URL
        value: wss://taskmanager-backend.onrender.com
      - key: GENERATE_SOURCEMAP
        value: "false"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Environment Groups (optional - for shared environment variables)
envVarGroups:
  - name: shared-config
    envVars:
      - key: NODE_ENV
        value: production
      - key: TZ
        value: UTC