# Generated by Django 5.2.6 on 2025-09-19 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClaudeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='Your Claude API key from Anthropic', max_length=255)),
                ('model', models.CharField(choices=[('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku'), ('claude-3-opus-20240229', 'Claude 3 Opus')], default='claude-3-5-sonnet-20241022', help_text='Claude model to use for AI suggestions', max_length=50)),
                ('max_tokens', models.IntegerField(default=4096, help_text='Maximum tokens per response')),
                ('temperature', models.FloatField(default=0.7, help_text='Response creativity (0.0-1.0)')),
                ('is_active', models.BooleanField(default=False, help_text='Whether AI features are enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claude_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Claude Settings',
                'verbose_name_plural': 'User Claude Settings',
                'db_table': 'user_claude_settings',
            },
        ),
    ]
