# Generated by Django 5.2.5 on 2025-08-22 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0, help_text='Task completion progress (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='task',
            name='velocity',
            field=models.CharField(choices=[('slow', 'Slow'), ('normal', 'Normal'), ('fast', 'Fast'), ('urgent', 'Urgent')], default='normal', help_text='Task development velocity', max_length=10),
        ),
    ]
